### ISSUE TITLE
Problem with pytorch

### ISSUE THREAD

**Issue by Ch4ndelier** [ruohoruotsi/LSTM-Music-Genre-Classification#12]
in  `lstm_genre_classifier_pytorch.py` file
`model.hidden = model.init_hidden()` actually does not work.
**Beacause model has no attribute 'hidden'**
if you print model.hidden in every batch,you will find it's always [[0,0,...]]
`model.hidden` has no relation with the actual model. It's just something you define every epoch.
So it's always a stateful LSTM.

**Comment by ruohoruotsi** [comment]
Thank you for the comment!! Can I invite you to submit a PR with your proposed solution? And maybe some context/explanation why `init_hidden()` isn't working. For example, was it deprecated, is there a bug in pytorch, did I use it incorrectly?

**Comment by Ch4ndelier** [comment]
`model.hidden = model.init_hidden()` isn't working because 'LSTM'  object originally has no attibute 'hidden'.
`hidden` used in method`forward` has no relation to `model.hidden`.
see https://pytorch.org/docs/stable/generated/torch.nn.LSTM.html?highlight=lstm#torch.nn.LSTM
since you  do not provide `(h_0, c_0)` in `lstm_out, hidden = self.lstm(input)`, both **h_0** and **c_0** will default to zero every batch.
so lstm won't be stateful between epochs, not even between batches(I said it's always stateful when I first commented, which is wrong, I apologize).
I've submited a PR(romove some unnecessary code and a solution to keep lstm stateful between batches), hope you'll see it.

**Comment by ruohoruotsi** [comment]
Thank you for this, re-reading your initial comment, I was initially confused by your "always stateful" remark. I've fully read your comments and clarification and I fully understand. Thank you very much for this. I'm still learning PyTorch and I see I have some details to master! Merging your PR now. Apologies for the very long delay, it's been interesting times 🙇
