### ISSUE TITLE
one question in feature extraction 

### ISSUE THREAD

**Issue by fttaheri** [ruohoruotsi/LSTM-Music-Genre-Classification#5]
Could you please let me know about 
data[i, :, 0:13] = mfcc.T[0:self.timeseries_length, :]
            data[i, :, 13:14] = spectral_center.T[0:self.timeseries_length, :]
            data[i, :, 14:26] = chroma.T[0:self.timeseries_length, :]
            data[i, :, 26:33] = spectral_contrast.T[0:self.timeseries_length, :]
 I don't know what is 0:13?
and 13:14?
thanks

**Comment by ruohoruotsi** [comment]
Hi there, `data` is just the feature vector that we're populating with different features. We append smaller lists of single audio features one after another.  So we have 13 MFCCs values (`0:13`) to which we append 1 spectral center (`13:14`), then 12 chroma features (`14:26`), etc. This way we construct an input vector comprising many different kinds of features and send the whole thing to the neural-network.

If you're not familiar with Python's colon notation for "slicing lists" the please have a look here, it'll help the code make more sense:

https://stackoverflow.com/questions/509211/understanding-slice-notation
https://www.youtube.com/watch?v=tKTZoB2Vjuk&feature=youtu.be&t=41m40s
