### ISSUE TITLE
Can we use .wav files?

### ISSUE THREAD

**Issue by dmumtaz** [ruohoruotsi/LSTM-Music-Genre-Classification#7]
I am trying to train my dataset containing .wav files but it throws errors when  I run the 
lstm_genre_classifier_keras.py file
**error:**
self.progbar.update(self.seen, self.log_values)
AttributeError: 'ProgbarLogger' object has no attribute 'log_values'

I have changed the line 151 in GenreFeatureData.py
from:
if file.endswith(".au"):
to
if file.endswith(".wav"):

**Comment by ruohoruotsi** [comment]
You can use WAVs if you want. `librosa`, the library that I use for reading the audiofiles reads WAVs as well, read their documentation though. See: https://github.com/ruohoruotsi/LSTM-Music-Genre-Classification/blob/master/GenreFeatureData.py#L104

As for your error, I don't see how `self.progbar.update` is related to the code in this repo? You should post the entire error message, so I have some context.

**Comment by dmumtaz** [comment]
Got it thanks!
