### ISSUE TITLE
How to generate model .json file?

### ISSUE THREAD

**Issue by dmumtaz** [ruohoruotsi/LSTM-Music-Genre-Classification#9]
I am training a different audio dataset on your code. 
For predicting the results, I have replaced **model_weights.h5** with **lstm_genre_classifier_lstm.h5** (generated during lstm training)  but need to know how to generate model .json file for my data?
**predict_example.py**
https://github.com/ruohoruotsi/LSTM-Music-Genre-Classification/blob/5f235f69e385a06c6a65da5e192c3ef11b0374ec/predict_example.py#L54
Also, in case I want to change the number of layers and the parameters associated with them, how to go about it?

**Comment by dmumtaz** [comment]
I solved the issue by referring to the article:
https://machinelearningmastery.com/save-load-keras-deep-learning-models/

You can add the following code at the end of lstm_genre_classifier.py file
```
print("creating .json file....")
model_json = model.to_json()
with open("model_new.json", "w") as json_file:
    json_file.write(model_json)
```

**Comment by ruohoruotsi** [comment]
Thanks for your comments on how your resolved this issue. Closing now.
